# Generated by Django 4.2.4 on 2023-08-31 23:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('complete', models.BooleanField(default=False)),
                ('priority', models.CharField(blank=True, choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High')], help_text='Task priority', max_length=1, null=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='todo.list')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
