# Generated by Django 4.2.4 on 2023-08-31 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='todo.list'),
        ),
    ]
