# Generated by Django 4.2.4 on 2023-10-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_user_inbox_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inbox_id',
            field=models.IntegerField(),
        ),
    ]
