# Generated by Django 4.2.4 on 2023-09-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_list_user_alter_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(blank=True, choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High')], default='l', help_text='Task priority', max_length=1, null=True),
        ),
    ]
