# Generated by Django 4.2.4 on 2023-09-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0, help_text='Task priority', null=True),
        ),
    ]
