# Generated by Django 4.2.4 on 2025-02-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_setting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='list',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
