# Generated by Django 4.2.4 on 2025-02-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_list_options_list_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='todo',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
