# Generated by Django 4.2.4 on 2023-09-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_todo_created_at_alter_todo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(blank=True, help_text='Task priority', null=True),
        ),
    ]
