# Generated by Django 4.2.4 on 2025-03-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_todo_options_todo_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='ordering',
            field=models.JSONField(default={'order': []}),
        ),
    ]
