# Generated by Django 4.2.4 on 2025-06-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_alter_todo_options_remove_todo_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
    ]
