/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `l` - Low
 * * `m` - Medium
 * * `h` - High
 * @export
 */
export const PriorityEnum = {
    L: 'l',
    M: 'm',
    H: 'h'
} as const;
export type PriorityEnum = typeof PriorityEnum[keyof typeof PriorityEnum];


export function PriorityEnumFromJSON(json: any): PriorityEnum {
    return PriorityEnumFromJSONTyped(json, false);
}

export function PriorityEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriorityEnum {
    return json as PriorityEnum;
}

export function PriorityEnumToJSON(value?: PriorityEnum | null): any {
    return value as any;
}

